$("#nav-btn").click(function(){
    $(".nav-menu").toggleClass("nav-active");
});
$("#nav-link").click(function(){
    $(".nav-menu").removeClass("nav-active");
});
$("#nav-link1").click(function(){
    $(".nav-menu").removeClass("nav-active");
});
$("#nav-link2").click(function(){
    $(".nav-menu").removeClass("nav-active");
});
$("#nav-link3").click(function(){
    $(".nav-menu").removeClass("nav-active");
});
$("#nav-close").click(function(){
    $(".nav-menu").removeClass("nav-active");
});